syntax = "proto3";

option csharp_namespace = "Catalog.API.Protos";

package catalog;

service CatalogGrpc {
  rpc GetCheckoutData (GetCheckoutDataRequest) returns (GetCheckoutDataResponse);
  rpc ValidateSeatLock (ValidateSeatLockRequest) returns (ValidateSeatLockResponse);
  rpc ValidateTicketTypes (ValidateTicketTypesRequest) returns (ValidateTicketTypesResponse);
}

message GetCheckoutDataRequest {
  string eventId = 1;
  string showtimeId = 2;
  repeated CheckoutRequestItem items = 3;
}

message CheckoutRequestItem {
  string seatId = 1;
  string ticketTypeId = 2;
  int32 quantity = 3;
}

message GetCheckoutDataResponse {
  bool isSuccess = 1;
  string message = 2;
  string eventTitle = 3;
  string organizerId = 4;
  string showtimeStartAt = 5;
  string showtimeEndAt = 6;
  repeated ValidatedCheckoutTicketItem ticketItems = 7;
  string organizerName = 8;
  string eventImage = 9;
}

message ValidatedCheckoutTicketItem {
  string seatId = 1;
  string ticketTypeId = 2;
  string ticketTypeName = 3;
  double price = 4;
  string seatName = 5;
  string rowName = 6;
  int32 quantity = 7;
}

message ValidateSeatLockRequest {
  string showtimeId = 1;
  repeated string seatIds = 2;
}

message ValidateSeatLockResponse {
  bool isSuccess = 1;
  string message = 2;
}

message ValidateTicketTypesRequest {
  string showtimeId = 1;
  repeated TicketTypeQuantityItem ticketItems = 2;
}

message TicketTypeQuantityItem {
  string ticketTypeId = 1;
  int32 quantity = 2;
}

message ValidateTicketTypesResponse {
  bool isSuccess = 1;
  string message = 2;
}
