<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.7" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.18" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
		<PackageReference Include="Microsoft.ML" Version="4.0.2" />
		<PackageReference Include="Microsoft.ML.Recommender" Version="0.22.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Contracts\BuildingBlocks.Contracts.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />
		<ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
		<ProjectReference Include="..\AI.Common\AI.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\catalog.proto" GrpcServices="Client" />
		<Protobuf Include="Protos\ordering.proto" GrpcServices="Client" />
	</ItemGroup>

</Project>
