<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="FluentValidation" Version="12.0.0" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
		<PackageReference Include="MediatR" Version="13.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Common\DTOs\Venues\" />
	  <Folder Include="Features\Venues\Commands\" />
	  <Folder Include="Features\Venues\Requests\" />
	  <Folder Include="Features\Venues\Validators\" />
	  <Folder Include="Features\Venues\Queries\" />
	</ItemGroup>

</Project>
